# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Abdi Noor
description:      ' Physicist/Tutor currently seeking new opportunities'
url:              http://abdi.io
baseurl:          /
logo:             /content/images/abdi2.png

author:
  name:           'Abdi Noor'
  url:

paginate:         5

disqus_shortname: abnoor

github:
  repo:           https://github.com/abnoor/abnoor.github.io

gems:
  - jekyll-sitemap

twitter: '@abdillest'

kramdown:
  # Enable GitHub Flavored Markdown (fenced code blocks)
  input: GFM
